FROM nginx:alpine

# Create log directories and files and set permissions
RUN mkdir -p /log/nginx && \
    touch /log/nginx/access.log && \
    touch /log/nginx/error.log && \
    chown -R nginx:nginx /log/nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf
