# Generated by Django 5.0 on 2023-12-20 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etoileconte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='body',
        ),
        migrations.AddField(
            model_name='story',
            name='audio_file',
            field=models.FileField(blank=True, help_text='The audio file of the story', null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time the story was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, help_text='The text of the story'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(help_text='The title of the story', max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the story was last updated'),
        ),
    ]
