# Generated by Django 5.0 on 2023-12-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etoileconte', '0002_remove_story_body_story_audio_file_story_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audio_file',
            field=models.FileField(blank=True, help_text='The audio file of the story', null=True, upload_to=''),
        ),
    ]
